###
# @name Basic

GET http://localhost:4004/odata/v4/catalog/Books

###
# @name BasicQuery
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{"name": "Authors to Deploy 1"}

###
# @name BasicDelete
DELETE http://localhost:4004/odata/v4/catalog/Authors(5abb6095-3f6e-4953-bc47-42b4e30ed8d4)

###
# @name BasicOrder
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{"book_ID": "201", "amount": 5}

###
# @name DeleteOrder
DELETE http://localhost:4004/odata/v4/catalog/Orders(aaf74810-f3c9-45af-a688-996be730472b)

###
# @name submitOrder
POST http://localhost:4004/odata/v4/catalog/submitOrder
Content-Type: application/json

{
    "book": "201",
    "amount": 10
}
